spring.application.name=service-registry
server.port = 8761

eureka.instance.hostname=localhost
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
eureka.server.evictionIntervalTimerInMs=30000
eureka.server.statusPageUrlUrl=127.0.0.1:8761/eureka/status
eureka.server.peerEurekaNodesUpdateIntervalMs=5000
eureka.server.lease-expiration-enabled=true
eureka.server.lease-renewal-interval-in-seconds=30
eureka.server.lease-expiration-duration-in-seconds=90
eureka.server.enable-self-preservation=false
# How often the server checks for expired leases (10 seconds)
eureka.server.eviction-interval-timer-in-ms=10000
